### ISSUE TITLE
Nuxt auth example serverless aws lambda cookie error

### ISSUE THREAD

**Issue by zgelp** [sidebase/nuxt-auth#300]
### Environment

Nuxt project info: (copied to clipboard)                                                                                                                                                                                      15:20:10

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.1.2`
- Nitro Version:    `2.1.2`
- Package Manager:  `npm@8.5.0`
- Builder:          `vite`
- User Config:      `css`, `modules`, `auth`
- Runtime Modules:  `@nuxtjs/tailwindcss@6.1.0`, `@sidebase/nuxt-auth@0.4.3`
- Build Modules:    `-`
------------------------------

### Reproduction

If you install serverless ( `npm install serverless serverless-offline`) , add 
``` 
nitro: {
    preset: 'aws-lambda',
    serveStatic: true,
  }
``` 
into nuxt.config.ts file to create aws-lambda build config and then build it with `nuxt build`, if you run it as lambda function with this serverless.yml config:

```
service: test-nuxt-app

provider:
  name: aws
  runtime: nodejs16.x
  stage: staging
  region: eu-central-1

plugins:
    - serverless-offline

package:
  patterns:
    - '!node_modules/**'
    - '!venv/**'
    - '!apienv/**'
    - '!__pycache__/**'

functions:
  nuxt:
    handler: .output/server/index.handler
    events:
      - httpApi: '*'
 ```
 With `serverless offline` command, you will get local reproduction of aws lambda and api gateway.

### Describe the bug

 The app fails on the initial render with this error:
 
 ```
 ANY /api/auth/csrf (λ: nuxt)
(λ: nuxt) RequestId: 6ffe7353-a747-49c1-904b-8695152fa163  Duration: 2.63 ms  Billed Duration: 3 ms
(λ: nuxt) RequestId: ad1a7548-57c8-4679-9457-cc26153f108c  Duration: 30.29 ms  Billed Duration: 31 ms
Debug: internal, implementation, error 
    Error: Invalid cookie name:  next-auth.callback-url
```

But if you end serverless offline comand and run it with `nuxt dev` command refresh the page, and then again with serverless-offline command, the `Invalid cookie name` error dissapears, app starts and you can login, but when you do with provided credentials it fails with error:

```
ANY /api/auth/callback/credentials (λ: nuxt)
(λ: nuxt) RequestId: e0896620-49b0-4a00-a0b6-b7e5dc3c1be4  Duration: 7.14 ms  Billed Duration: 8 ms
Debug: internal, implementation, error 
    Error: Invalid cookie name:  28 Apr 2023 13:27:43 GMT; HttpOnly; SameSite
```

### Additional context

The app only fails when builded with nitro `aws-lambda` preset, the library also works fine localy in dev environment, but similar and error that I can't reproduce localy happens when deployed with serverless to aws lambda and api gateway.
